import { NetworkMember } from "./types";

export const networkData: NetworkMember = {
  id: 1,
  full_name: "John Anderson",
  ucode: "john01",
  rcode: null,
  position: null,
  paid_status: 1,
  status: "Active",
  left_business: 84500,
  right_business: 69200,
  card_color: "green",
  children: [
    {
      id: 2,
      full_name: "Sarah Wilson",
      ucode: "sarah",
      rcode: "john01",
      position: "L",
      paid_status: 1,
      status: "Active",
      left_business: 34200,
      right_business: 22800,
      card_color: "green",
      children: [
        {
          id: 4,
          full_name: "Emma Smith",
          ucode: "emma",
          rcode: "sarah",
          position: "L",
          paid_status: 1,
          status: "Active",
          left_business: 5600,
          right_business: 8200,
          card_color: "yellow",
        },
        {
          id: 5,
          full_name: "David Brown",
          ucode: "david",
          rcode: "sarah",
          position: "R",
          paid_status: 0,
          status: "Inactive",
          left_business: 2800,
          right_business: 3500,
          card_color: "red",
        },
      ],
    },
    {
      id: 3,
      full_name: "Michael Johnson",
      ucode: "michael",
      rcode: "john01",
      position: "R",
      paid_status: 1,
      status: "Active",
      left_business: 26800,
      right_business: 31100,
      card_color: "green",
      children: [
        {
          id: 6,
          full_name: "Olivia Davis",
          ucode: "olivia",
          rcode: "michael",
          position: "L",
          paid_status: 1,
          status: "Active",
          left_business: 6400,
          right_business: 4700,
          card_color: "yellow",
        },
        {
          id: 7,
          full_name: "James Miller",
          ucode: "james",
          rcode: "michael",
          position: "R",
          paid_status: 1,
          status: "Active",
          left_business: 9100,
          right_business: 7600,
          card_color: "green",
        },
      ],
    },
  ],
};